# Set the default compiler to gcc
CC = gcc

# Set the flags
CFLAGS = -Wall -Wextra -Werror

# Files to run
SOURCES = my_mastermind.c
TARGET = my_mastermind

$(TARGET) : 
	$(CC) -o $@ $(SOURCES) $(CFLAGS)